targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en_US
          fallback_strategy: base_locale
          input_directory: lib/i18n
          output_directory: lib/app/langs
          flutter_integration: true
          key_case: camel
          string_interpolation: dart