import 'package:flutter/cupertino.dart';

import '../../app/icons/icon.dart';

class Country {
  final String code;
  final String name;
  final String threeLetterCode;

  const Country({
    required this.code,
    required this.name,
    required this.threeLetterCode,
  });

  factory Country.fromMap(Map<String, String> map) {
    return Country(
      code: map['code'] ?? '',
      name: map['name'] ?? '',
      threeLetterCode: map['threeLetterCode'] ?? '',
    );
  }

  Widget get icon =>
      ClipOval(child: MyIcon.iconFlagSquare("${code.toLowerCase()}.svg"));

  Map<String, String> toMap() {
    return {'code': code, 'name': name, 'threeLetterCode': threeLetterCode};
  }

  @override
  String toString() =>
      'Country(code: $code, name: $name, threeLetterCode: $threeLetterCode)';
}

const List<Country> countryList = [
  Country(code: "AF", name: "Afghanistan", threeLetterCode: "AFG"),
  Country(code: "AL", name: "Albania", threeLetterCode: "ALB"),
  Country(code: "DZ", name: "Algeria", threeLetterCode: "ALG"),
  Country(code: "AS", name: "American Samoa", threeLetterCode: "ASA"),
  Country(code: "AD", name: "Andorre", threeLetterCode: "AND"),
  Country(code: "AO", name: "Angola", threeLetterCode: "ANG"),
  Country(code: "AI", name: "Anguilla", threeLetterCode: "AIA"),
  Country(code: "AQ", name: "Antarctica", threeLetterCode: "ATA"),
  Country(code: "AG", name: "Antigua and Barbuda", threeLetterCode: "ATG"),
  Country(code: "AR", name: "Argentina", threeLetterCode: "ARG"),
  Country(code: "AM", name: "Armenia", threeLetterCode: "ARM"),
  Country(code: "AW", name: "Aruba", threeLetterCode: "ARU"),
  Country(code: "AU", name: "Australia", threeLetterCode: "AUS"),
  Country(code: "AT", name: "Austria", threeLetterCode: "AUT"),
  Country(code: "AZ", name: "Azerbaijan", threeLetterCode: "AZE"),
  Country(code: "BS", name: "Bahamas", threeLetterCode: "BAH"),
  Country(code: "BH", name: "Bahrain", threeLetterCode: "BHR"),
  Country(code: "BD", name: "Bangladesh", threeLetterCode: "BAN"),
  Country(code: "BB", name: "Barbade", threeLetterCode: "BRB"),
  Country(code: "BY", name: "Belarus", threeLetterCode: "BLR"),
  Country(code: "BE", name: "Belgium", threeLetterCode: "BEL"),
  Country(code: "BZ", name: "Belize", threeLetterCode: "BLZ"),
  Country(code: "BJ", name: "Benin", threeLetterCode: "BEN"),
  Country(code: "BM", name: "Bermuda", threeLetterCode: "BER"),
  Country(code: "BT", name: "Bhutan", threeLetterCode: "BHU"),
  Country(code: "BO", name: "Bolivia", threeLetterCode: "BOL"),
  Country(
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    threeLetterCode: "BES",
  ),
  Country(code: "BA", name: "Bosnia & Herzegovina", threeLetterCode: "BIH"),
  Country(code: "BW", name: "Botswana", threeLetterCode: "BOT"),
  Country(code: "BV", name: "Bouvet Island", threeLetterCode: "BVT"),
  Country(code: "BR", name: "Brazil", threeLetterCode: "BRA"),
  Country(
    code: "IO",
    name: "British Indian Ocean Territory",
    threeLetterCode: "IOT",
  ),
  Country(code: "VG", name: "British Virgin Islands", threeLetterCode: "VGB"),
  Country(code: "BN", name: "Brunei", threeLetterCode: "BRU"),
  Country(code: "BG", name: "Bulgaria", threeLetterCode: "BUL"),
  Country(code: "BF", name: "Burkina Faso", threeLetterCode: "BFA"),
  Country(code: "BI", name: "Burundi", threeLetterCode: "BDI"),
  Country(code: "KH", name: "Cambodia", threeLetterCode: "CAM"),
  Country(code: "CM", name: "Cameroon", threeLetterCode: "CMR"),
  Country(code: "CA", name: "Canada", threeLetterCode: "CAN"),
  Country(code: "CV", name: "Cape Verde", threeLetterCode: "CPV"),
  Country(code: "KY", name: "Cayman Islands", threeLetterCode: "CAY"),
  Country(code: "CF", name: "Central African Republic", threeLetterCode: "CTA"),
  Country(code: "TD", name: "Chad", threeLetterCode: "CHA"),
  Country(code: "CL", name: "Chile", threeLetterCode: "CHI"),
  Country(code: "CN", name: "China", threeLetterCode: "CHN"),
  Country(code: "CX", name: "Christmas Island", threeLetterCode: "CXR"),
  Country(code: "CC", name: "Cocos (Keeling) Islands", threeLetterCode: "CCK"),
  Country(code: "CO", name: "Colombia", threeLetterCode: "COL"),
  Country(code: "KM", name: "Comoros", threeLetterCode: "COM"),
  Country(code: "CG", name: "Congo", threeLetterCode: "CGO"),
  Country(code: "CD", name: "Congo (Dem. Rep.)", threeLetterCode: "COD"),
  Country(code: "CK", name: "Cook Islands", threeLetterCode: "COK"),
  Country(code: "CR", name: "Costa Rica", threeLetterCode: "CRC"),
  Country(code: "ME", name: "Montenegro", threeLetterCode: "MNE"),
  Country(code: "HR", name: "Croatia", threeLetterCode: "CRO"),
  Country(code: "CU", name: "Cuba", threeLetterCode: "CUB"),
  Country(code: "CW", name: "Curaçao", threeLetterCode: "CUW"),
  Country(code: "CY", name: "Cyprus", threeLetterCode: "CYP"),
  Country(code: "CZ", name: "Czech Republic", threeLetterCode: "CZE"),
  Country(code: "CI", name: "Côte D'Ivoire", threeLetterCode: "CIV"),
  Country(code: "DK", name: "Denmark", threeLetterCode: "DEN"),
  Country(code: "DJ", name: "Djibouti", threeLetterCode: "DJI"),
  Country(code: "DM", name: "Dominica", threeLetterCode: "DMA"),
  Country(code: "DO", name: "Dominican Republic", threeLetterCode: "DOM"),
  Country(code: "TL", name: "East Timor", threeLetterCode: "TLS"),
  Country(code: "EC", name: "Ecuador", threeLetterCode: "ECU"),
  Country(code: "EG", name: "Egypt", threeLetterCode: "EGY"),
  Country(code: "SV", name: "El Salvador", threeLetterCode: "SLV"),
  Country(code: "GQ", name: "Equatorial Guinea", threeLetterCode: "EQG"),
  Country(code: "ER", name: "Eritrea", threeLetterCode: "ERI"),
  Country(code: "EE", name: "Estonia", threeLetterCode: "EST"),
  Country(code: "ET", name: "Ethiopia", threeLetterCode: "ETH"),
  Country(code: "FK", name: "Falkland Islands", threeLetterCode: "FLK"),
  Country(code: "FO", name: "Faroe Islands", threeLetterCode: "FRO"),
  Country(code: "FJ", name: "Fiji", threeLetterCode: "FIJ"),
  Country(code: "FI", name: "Finland", threeLetterCode: "FIN"),
  Country(code: "FR", name: "France", threeLetterCode: "FRA"),
  Country(code: "GF", name: "French Guiana", threeLetterCode: "GUF"),
  Country(code: "PF", name: "French Polynesia", threeLetterCode: "TAH"),
  Country(
    code: "TF",
    name: "French Southern Territories",
    threeLetterCode: "ATF",
  ),
  Country(code: "GA", name: "Gabon", threeLetterCode: "GAB"),
  Country(code: "GM", name: "Gambia", threeLetterCode: "GAM"),
  Country(code: "GE", name: "Georgia", threeLetterCode: "GEO"),
  Country(code: "DE", name: "Germany", threeLetterCode: "GER"),
  Country(code: "GH", name: "Ghana", threeLetterCode: "GHA"),
  Country(code: "GI", name: "Gibraltar", threeLetterCode: "GIB"),
  Country(code: "GR", name: "Greece", threeLetterCode: "GRE"),
  Country(code: "GL", name: "Greenland", threeLetterCode: "GRL"),
  Country(code: "GD", name: "Grenada", threeLetterCode: "GRN"),
  Country(code: "GP", name: "Guadeloupe", threeLetterCode: "GLP"),
  Country(code: "GU", name: "Guam", threeLetterCode: "GUM"),
  Country(code: "GT", name: "Guatemala", threeLetterCode: "GUA"),
  Country(code: "GG", name: "Guernsey and Alderney", threeLetterCode: "GGY"),
  Country(code: "GN", name: "Guinea", threeLetterCode: "GUI"),
  Country(code: "GW", name: "Guinea-Bissau", threeLetterCode: "GNB"),
  Country(code: "GY", name: "Guyana", threeLetterCode: "GUY"),
  Country(code: "HT", name: "Haiti", threeLetterCode: "HAI"),
  Country(
    code: "HM",
    name: "Heard and McDonald Islands",
    threeLetterCode: "HMD",
  ),
  Country(code: "HN", name: "Honduras", threeLetterCode: "HON"),
  Country(code: "HK", name: "Hong Kong", threeLetterCode: "HKG"),
  Country(code: "HU", name: "Hungary", threeLetterCode: "HUN"),
  Country(code: "IS", name: "Iceland", threeLetterCode: "ISL"),
  Country(code: "IN", name: "India", threeLetterCode: "IND"),
  Country(code: "ID", name: "Indonesia", threeLetterCode: "IDN"),
  Country(code: "IR", name: "Iran", threeLetterCode: "IRN"),
  Country(code: "IQ", name: "Iraq", threeLetterCode: "IRQ"),
  Country(code: "IE", name: "Ireland", threeLetterCode: "IRL"),
  Country(code: "IM", name: "Isle of Man", threeLetterCode: "IMN"),
  Country(code: "IL", name: "Israel", threeLetterCode: "ISR"),
  Country(code: "IT", name: "Italy", threeLetterCode: "ITA"),
  Country(code: "JM", name: "Jamaica", threeLetterCode: "JAM"),
  Country(code: "JP", name: "Japan", threeLetterCode: "JPN"),
  Country(code: "JE", name: "Jersey", threeLetterCode: "JEY"),
  Country(code: "JO", name: "Jordan", threeLetterCode: "JOR"),
  Country(code: "KZ", name: "Kazakhstan", threeLetterCode: "KAZ"),
  Country(code: "KE", name: "Kenya", threeLetterCode: "KEN"),
  Country(code: "KI", name: "Kiribati", threeLetterCode: "KIR"),
  Country(code: "KP", name: "Korea (North)", threeLetterCode: "PRK"),
  Country(code: "KR", name: "Korea (South)", threeLetterCode: "KOR"),
  Country(code: "KR", name: "South Korea", threeLetterCode: "KOR"),
  Country(code: "KW", name: "Kuwait", threeLetterCode: "KUW"),
  Country(code: "KG", name: "Kyrgyzstan", threeLetterCode: "KGZ"),
  Country(code: "LA", name: "Laos", threeLetterCode: "LAO"),
  Country(code: "LV", name: "Latvia", threeLetterCode: "LVA"),
  Country(code: "LB", name: "Lebanon", threeLetterCode: "LBN"),
  Country(code: "LS", name: "Lesotho", threeLetterCode: "LES"),
  Country(code: "LR", name: "Liberia", threeLetterCode: "LBR"),
  Country(code: "LY", name: "Libya", threeLetterCode: "LBY"),
  Country(code: "LI", name: "Liechtenstein", threeLetterCode: "LIE"),
  Country(code: "LT", name: "Lithuania", threeLetterCode: "LTU"),
  Country(code: "LU", name: "Luxembourg", threeLetterCode: "LUX"),
  Country(code: "MO", name: "Macao", threeLetterCode: "MAC"),
  Country(code: "MK", name: "Macedonia", threeLetterCode: "MKD"),
  Country(code: "MG", name: "Madagascar", threeLetterCode: "MAD"),
  Country(code: "MW", name: "Malawi", threeLetterCode: "MWI"),
  Country(code: "MY", name: "Malaysia", threeLetterCode: "MAS"),
  Country(code: "MV", name: "Maldives", threeLetterCode: "MDV"),
  Country(code: "ML", name: "Mali", threeLetterCode: "MLI"),
  Country(code: "MT", name: "Malta", threeLetterCode: "MLT"),
  Country(code: "MH", name: "Marshall Islands", threeLetterCode: "MHL"),
  Country(code: "MQ", name: "Martinique", threeLetterCode: "MTQ"),
  Country(code: "MR", name: "Mauritania", threeLetterCode: "MTN"),
  Country(code: "MU", name: "Mauritius", threeLetterCode: "MRI"),
  Country(code: "YT", name: "Mayotte", threeLetterCode: "MYT"),
  Country(code: "MX", name: "Mexico", threeLetterCode: "MEX"),
  Country(code: "FM", name: "Micronesia", threeLetterCode: "FSM"),
  Country(code: "MD", name: "Moldova", threeLetterCode: "MDA"),
  Country(code: "MC", name: "Monaco", threeLetterCode: "MCO"),
  Country(code: "MN", name: "Mongolia", threeLetterCode: "MNG"),
  Country(code: "MS", name: "Montserrat", threeLetterCode: "MSR"),
  Country(code: "MA", name: "Morocco", threeLetterCode: "MAR"),
  Country(code: "MZ", name: "Mozambique", threeLetterCode: "MOZ"),
  Country(code: "MM", name: "Myanmar", threeLetterCode: "MYA"),
  Country(code: "NA", name: "Namibia", threeLetterCode: "NAM"),
  Country(code: "NR", name: "Nauru", threeLetterCode: "NRU"),
  Country(code: "NP", name: "Nepal", threeLetterCode: "NEP"),
  Country(code: "NL", name: "Netherlands", threeLetterCode: "NED"),
  Country(code: "NL", name: "Netherlands Antilles", threeLetterCode: "ANT"),
  Country(code: "NC", name: "New Caledonia", threeLetterCode: "NCL"),
  Country(code: "NZ", name: "New Zealand", threeLetterCode: "NZL"),
  Country(code: "NI", name: "Nicaragua", threeLetterCode: "NCA"),
  Country(code: "NE", name: "Niger", threeLetterCode: "NIG"),
  Country(code: "NG", name: "Nigeria", threeLetterCode: "NGA"),
  Country(code: "NU", name: "Niue", threeLetterCode: "NIU"),
  Country(code: "NF", name: "Norfolk Island", threeLetterCode: "NFK"),
  Country(code: "MP", name: "Northern Mariana Islands", threeLetterCode: "MNP"),
  Country(code: "NO", name: "Norway", threeLetterCode: "NOR"),
  Country(code: "OM", name: "Oman", threeLetterCode: "OMA"),
  Country(code: "PK", name: "Pakistan", threeLetterCode: "PAK"),
  Country(code: "PW", name: "Palau", threeLetterCode: "PLW"),
  Country(code: "PS", name: "Palestine", threeLetterCode: "PLE"),
  Country(code: "PA", name: "Panama", threeLetterCode: "PAN"),
  Country(code: "PG", name: "Papua New Guinea", threeLetterCode: "PNG"),
  Country(code: "PY", name: "Paraguay", threeLetterCode: "PAR"),
  Country(code: "PE", name: "Peru", threeLetterCode: "PER"),
  Country(code: "PH", name: "Philippines", threeLetterCode: "PHI"),
  Country(code: "PN", name: "Pitcairn", threeLetterCode: "PCN"),
  Country(code: "PL", name: "Poland", threeLetterCode: "POL"),
  Country(code: "PT", name: "Portugal", threeLetterCode: "POR"),
  Country(code: "PR", name: "Puerto Rico", threeLetterCode: "PUR"),
  Country(code: "QA", name: "Qatar", threeLetterCode: "QAT"),
  Country(code: "RO", name: "Romania", threeLetterCode: "ROU"),
  Country(code: "RU", name: "Russia", threeLetterCode: "RUS"),
  Country(code: "RW", name: "Rwanda", threeLetterCode: "RWA"),
  Country(code: "RE", name: "Réunion", threeLetterCode: "REU"),
  Country(code: "BL", name: "Saint Barthélemy", threeLetterCode: "BLM"),
  Country(code: "SH", name: "Saint Helena", threeLetterCode: "SHN"),
  Country(code: "KN", name: "Saint Kitts and Nevis", threeLetterCode: "SKN"),
  Country(code: "LC", name: "Saint Lucia", threeLetterCode: "LCA"),
  Country(code: "MF", name: "Saint Martin", threeLetterCode: "MAF"),
  Country(
    code: "PM",
    name: "Saint Pierre and Miquelon",
    threeLetterCode: "SPM",
  ),
  Country(
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    threeLetterCode: "VIN",
  ),
  Country(code: "WS", name: "Samoa", threeLetterCode: "SAM"),
  Country(code: "SM", name: "San Marino", threeLetterCode: "SMR"),
  Country(code: "SA", name: "Saudi Arabia", threeLetterCode: "KSA"),
  Country(code: "SN", name: "Senegal", threeLetterCode: "SEN"),
  Country(code: "RS", name: "Serbia", threeLetterCode: "SRB"),
  Country(code: "SC", name: "Seychelles", threeLetterCode: "SEY"),
  Country(code: "SL", name: "Sierra Leone", threeLetterCode: "SLE"),
  Country(code: "SG", name: "Singapore", threeLetterCode: "SIN"),
  Country(code: "SX", name: "Sint Maarten", threeLetterCode: "SXM"),
  Country(code: "SK", name: "Slovakia", threeLetterCode: "SVK"),
  Country(code: "SI", name: "Slovenia", threeLetterCode: "SVN"),
  Country(code: "SB", name: "Solomon Islands", threeLetterCode: "SOL"),
  Country(code: "SO", name: "Somalia", threeLetterCode: "SOM"),
  Country(code: "ZA", name: "South Africa", threeLetterCode: "RSA"),
  Country(
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    threeLetterCode: "SGS",
  ),
  Country(code: "SS", name: "South Sudan", threeLetterCode: "SSD"),
  Country(code: "ES", name: "Spain", threeLetterCode: "ESP"),
  Country(code: "LK", name: "Sri Lanka", threeLetterCode: "SRI"),
  Country(code: "SD", name: "Sudan", threeLetterCode: "SDN"),
  Country(code: "SR", name: "Suriname", threeLetterCode: "SUR"),
  Country(code: "SJ", name: "Svalbard and Jan Mayen", threeLetterCode: "SJM"),
  Country(code: "SZ", name: "Swaziland", threeLetterCode: "SWZ"),
  Country(code: "SE", name: "Sweden", threeLetterCode: "SWE"),
  Country(code: "CH", name: "Switzerland", threeLetterCode: "SUI"),
  Country(code: "SY", name: "Syria", threeLetterCode: "SYR"),
  Country(code: "ST", name: "São Tomé and Príncipe", threeLetterCode: "STP"),
  Country(code: "TW", name: "Taiwan", threeLetterCode: "TPE"),
  Country(code: "TJ", name: "Tajikistan", threeLetterCode: "TJK"),
  Country(code: "TZ", name: "Tanzania", threeLetterCode: "TAN"),
  Country(code: "TH", name: "Thailand", threeLetterCode: "THA"),
  Country(code: "TG", name: "Togo", threeLetterCode: "TOG"),
  Country(code: "TK", name: "Tokelau", threeLetterCode: "TKL"),
  Country(code: "TO", name: "Tonga", threeLetterCode: "TGA"),
  Country(code: "TT", name: "Trinidad & Tobago", threeLetterCode: "TRI"),
  Country(code: "TN", name: "Tunisia", threeLetterCode: "TUN"),
  Country(code: "TR", name: "Turkey", threeLetterCode: "TUR"),
  Country(code: "TM", name: "Turkmenistan", threeLetterCode: "TKM"),
  Country(code: "TC", name: "Turks and Caicos Islands", threeLetterCode: "TCA"),
  Country(code: "TV", name: "Tuvalu", threeLetterCode: "TUV"),
  Country(code: "UG", name: "Uganda", threeLetterCode: "UGA"),
  Country(code: "UA", name: "Ukraine", threeLetterCode: "UKR"),
  Country(code: "AE", name: "United Arab Emirates", threeLetterCode: "UAE"),
  Country(code: "GB", name: "United Kingdom", threeLetterCode: "GBR"),
  Country(code: "GB-ENG", name: "England", threeLetterCode: "ENG"),
  Country(code: "GB-WLS", name: "Wales", threeLetterCode: "WLS"),
  Country(code: "GB-SCT", name: "Scotland", threeLetterCode: "SCT"),
  Country(code: "GB-NIR", name: "Northern Ireland", threeLetterCode: "NIR"),
  Country(
    code: "UM",
    name: "United States Minor Outlying Islands",
    threeLetterCode: "UMI",
  ),
  Country(code: "US", name: "United States of America", threeLetterCode: "USA"),
  Country(code: "US", name: "USA", threeLetterCode: "USA"),
  Country(code: "UY", name: "Uruguay", threeLetterCode: "URU"),
  Country(code: "UZ", name: "Uzbekistan", threeLetterCode: "UZB"),
  Country(code: "VU", name: "Vanuatu", threeLetterCode: "VAN"),
  Country(code: "VA", name: "Vatican City", threeLetterCode: "VAT"),
  Country(code: "VE", name: "Venezuela", threeLetterCode: "VEN"),
  Country(code: "VN", name: "Vietnam", threeLetterCode: "VIE"),
  Country(
    code: "VI",
    name: "Virgin Islands of the United States",
    threeLetterCode: "VIR",
  ),
  Country(code: "WF", name: "Wallis and Futuna", threeLetterCode: "WLF"),
  Country(code: "EH", name: "Western Sahara", threeLetterCode: "ESH"),
  Country(code: "YE", name: "Yemen", threeLetterCode: "YEM"),
  Country(code: "ZM", name: "Zambia", threeLetterCode: "ZAM"),
  Country(code: "ZW", name: "Zimbabwe", threeLetterCode: "ZIM"),
  Country(code: "AX", name: "Åland Islands", threeLetterCode: "ALA"),
];

/// 根据 name 获取 Country 实例
Country? getCountryByName(String name) {
  try {
    return countryList.firstWhere(
      (c) => c.name.toLowerCase() == name.toLowerCase(),
    );
  } catch (e) {
    return null;
  }
}
